### ISSUE TITLE
Fix: No text for code search

### ISSUE THREAD

**Issue by jbessi** [eonum/medcodesearch-frontend#15]
f.e. [(https://www.google.com/url?q=https://medcodesearch.ch/de/ICD/ICD10-GM-2021/icds/N81?query%3DN81&sa=D&source=hangouts&ust=1624188834902000&usg=AFQjCNE20j8-9Q-8UgpzN11NyDXURSrhlg)]

When reverting to commit 96225693434292e27800b3e37458409d6a4b874f (before PSE), it is working.

**Comment by tschimbr** [comment]
See 02b76b8
